language: python
python:
    - '3.5'
before_install:
    - echo "data_dir="~/"; plot_dir="~/"; fig_size=(12, 8);" > CryptoForecast/config.py
install:
    - pip install -r requirements.txt
before_script:
    - luigid &
script:
    - nosetests
